feat: add dashboard 404 route
TailAdmin/free-react-tailwind-admin-dashboard pull request #27
Opened 2024-07-03 20:38 UTC by luigimorel

-  Add a NotFound wildcard route to handle routes that do not exist in the application

2024-07-26 16:17 UTC, tuvuanh27 requested changes

2024-07-26 16:17 UTC, tuvuanh27 commented on src/pages/NotFound.tsx
> +  const naviagate = useNavigate();
navigate

2024-07-27 16:09 UTC, luigimorel commented on src/pages/NotFound.tsx
> +  const naviagate = useNavigate();
Fixed

2024-10-05 21:40 UTC, luigimorel commented
I no longer want to work on this.

2024-10-05 21:40 UTC, closed without merging